import dataclasses
import enum
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional, Union


class PipelineStatus(enum.Enum):
    """Enumeration for the current status of the code generation pipeline."""
    PENDING = "PENDING"
    INITIALIZING = "INITIALIZING"
    PLANNING = "PLANNING"
    CODING = "CODING"
    LINTING = "LINTING"
    TESTING = "TESTING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class Severity(enum.Enum):
    """Enumeration for the severity of a linting or test issue."""
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"


@dataclass(frozen=True)
class LintIssue:
    """Represents a single issue found by a linter.

    This is an immutable data class to ensure that once a lint issue is
    recorded, it cannot be altered.

    Attributes:
        file_path (Path): The path to the file where the issue was found.
        line_number (int): The line number of the issue.
        column_number (int): The column number where the issue starts.
        code (str): The specific error code or identifier (e.g., 'E501').
        message (str): A human-readable description of the issue.
        severity (Severity): The severity level of the issue.
    """
    file_path: Path
    line_number: int
    column_number: int
    code: str
    message: str
    severity: Severity = Severity.WARNING


@dataclass
class LintingResult:
    """Stores the complete results from a single linter run.

    Attributes:
        linter_name (str): The name of the linter tool used (e.g., 'pylint', 'flake8').
        success (bool): True if the linter passed without any critical errors, False otherwise.
        issues (List[LintIssue]): A list of all issues found by the linter.
        raw_output (str): The raw, unprocessed output from the linter command.
        execution_time (float): Time taken for the linter to run, in seconds.
    """
    linter_name: str
    success: bool = True
    issues: List[LintIssue] = field(default_factory=list)
    raw_output: str = ""
    execution_time: float = 0.0


@dataclass
class TestResult:
    """Stores the results from a single test runner execution.

    Attributes:
        test_runner (str): The name of the test runner (e.g., 'pytest').
        success (bool): True if all tests passed, False otherwise.
        tests_run (int): The total number of tests executed.
        tests_passed (int): The number of tests that passed.
        tests_failed (int): The number of tests that failed.
        tests_skipped (int): The number of tests that were skipped.
        raw_output (str): The raw, unprocessed output from the test runner.
        execution_time (float): Time taken for the tests to run, in seconds.
    """
    test_runner: str
    success: bool = True
    tests_run: int = 0
    tests_passed: int = 0
    tests_failed: int = 0
    tests_skipped: int = 0
    raw_output: str = ""
    execution_time: float = 0.0


@dataclass
class CodeFile:
    """Represents a single file with its content and metadata.

    This class helps manage individual files within the context of a larger
    code generation task, which may involve creating or modifying multiple files.

    Attributes:
        path (Path): The relative path of the file from the project root.
        content (str): The source code or text content of the file.
        is_new (bool): True if the file was newly created in this session.
        is_modified (bool): True if an existing file was modified.
    """
    path: Path
    content: str
    is_new: bool = True
    is_modified: bool = False


@dataclass
class PipelineContext:
    """
    A state container for the entire code generation pipeline.

    This data class holds all data relevant to a single code generation task
    as it moves through the various stages of the pipeline, from initial
    requirements to final testing. It serves as the single source of truth
    for the pipeline's state.

    Attributes:
        session_id (uuid.UUID): A unique identifier for this pipeline run.
        initial_requirements (str): The original, unmodified user prompt.
        project_root (Path): The root directory for the generated code.
        status (PipelineStatus): The current status of the pipeline.
        plan (Optional[str]): The detailed plan generated by the planning stage.
        generated_files (Dict[Path, CodeFile]): A dictionary mapping file paths
            to their corresponding CodeFile objects.
        linting_results (List[LintingResult]): A list of results from all
            linter runs.
        test_results (List[TestResult]): A list of results from all
            test runner executions.
        error_message (Optional[str]): If the pipeline fails, this holds the
            reason.
        start_time (datetime): The UTC timestamp when the pipeline was initiated.
        end_time (Optional[datetime]): The UTC timestamp when the pipeline
            concluded (either completed or failed).
        history (List[str]): A log of major events or status changes.
    """
    initial_requirements: str
    project_root: Path
    session_id: uuid.UUID = field(default_factory=uuid.uuid4)
    status: PipelineStatus = field(default=PipelineStatus.PENDING)
    plan: Optional[str] = None
    generated_files: Dict[Path, CodeFile] = field(default_factory=dict)
    linting_results: List[LintingResult] = field(default_factory=list)
    test_results: List[TestResult] = field(default_factory=list)
    error_message: Optional[str] = None
    start_time: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    end_time: Optional[datetime] = None
    history: List[str] = field(default_factory=list)

    def __post_init__(self):
        """Initializes the context after creation."""
        self.update_status(PipelineStatus.INITIALIZING, "Context initialized.")

    def update_status(self, new_status: PipelineStatus, message: Optional[str] = None):
        """
        Updates the pipeline's status and logs the change to history.

        Args:
            new_status (PipelineStatus): The new status to set.
            message (Optional[str]): An optional message describing the event.
        """
        self.status = new_status
        timestamp = datetime.now(timezone.utc).isoformat()
        log_entry = f"[{timestamp}] Status changed to {new_status.name}"
        if message:
            log_entry += f": {message}"
        self.history.append(log_entry)

    def add_code_file(self, file_path: Union[str, Path], content: str, is_new: bool = True, is_modified: bool = False):
        """
        Adds or updates a generated code file in the context.

        Args:
            file_path (Union[str, Path]): The relative path of the file.
            content (str): The content of the file.
            is_new (bool): Flag indicating if the file is new.
            is_modified (bool): Flag indicating if the file was modified.
        """
        path_obj = Path(file_path) if isinstance(file_path, str) else file_path
        code_file = CodeFile(
            path=path_obj,
            content=content,
            is_new=is_new,
            is_modified=is_modified
        )
        self.generated_files[path_obj] = code_file
        self.history.append(f"Added/Updated file: {path_obj}")

    def get_code_file(self, file_path: Union[str, Path]) -> Optional[CodeFile]:
        """
        Retrieves a CodeFile object by its path.

        Args:
            file_path (Union[str, Path]): The relative path of the file.

        Returns:
            Optional[CodeFile]: The CodeFile object if it exists, otherwise None.
        """
        path_obj = Path(file_path) if isinstance(file_path, str) else file_path
        return self.generated_files.get(path_obj)

    def get_all_code_content(self) -> str:
        """
        Concatenates the content of all generated files.

        Returns:
            str: A single string containing all code, separated by a header
                 indicating the file path.
        """
        full_content = []
        for path, code_file in sorted(self.generated_files.items()):
            header = f"\n--- FILE: {path} ---\n"
            full_content.append(header)
            full_content.append(code_file.content)
        return "".join(full_content)

    def fail(self, message: str):
        """
        Marks the pipeline as FAILED and records the final state.

        Args:
            message (str): The error message explaining the failure.
        """
        self.error_message = message
        self.update_status(PipelineStatus.FAILED, message)
        self.end_time = datetime.now(timezone.utc)

    def complete(self):
        """Marks the pipeline as COMPLETED and records the end time."""
        if self.status != PipelineStatus.FAILED:
            self.update_status(PipelineStatus.COMPLETED, "Pipeline finished successfully.")
            self.end_time = datetime.now(timezone.utc)

    @property
    def duration(self) -> Optional[float]:
        """
        Calculates the total duration of the pipeline in seconds.

        Returns:
            Optional[float]: The duration in seconds if the pipeline has
                             finished, otherwise None.
        """
        if self.end_time:
            return (self.end_time - self.start_time).total_seconds()
        return None

    @property
    def has_critical_failures(self) -> bool:
        """
        Checks if there are any critical linting or test failures.

        Returns:
            bool: True if any linter or test run reported a failure,
                  False otherwise.
        """
        lint_failed = any(not result.success for result in self.linting_results)
        test_failed = any(not result.success for result in self.test_results)
        return lint_failed or test_failed
